---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - networking.yaml
  - infrastructure.yaml
  - gateway-api-crds.yaml
  - configs.yaml
  - cloudflare-gateway-controller.yaml
  - apps.yaml
