apiVersion: v1
kind: Secret
metadata:
    name: nightscout-secret-values
    namespace: nightscout
stringData:
    values.yaml: ENC[AES256_GCM,data:Y95sJeCr8nNAcJyX+bk6i6VNO/+Sh33JfC9/6yUE05pndFmwdbR6E1VmsvXJ00pg7eiLdicYkRuBVQ==,iv:E1MZK6wZU07FsPpLt/RwaLTgN1te2N/+RnBkIX7M4wM=,tag:eM8b+OPzbBq6vyIbnM9MTA==,type:str]
sops:
    age:
        - recipient: age1khuydqqhtu0wj8nx6kgkfgw6wrvff09p864fzjsw34vtp0pjr50q8dvpcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUXZYbWlFRWg4Zi9LWHg5
            VmtqZ1Yvb05BMlozUEgxdTdlWklraEwyWmk0ClU5ZkZWZHZGTEtWa09Ia1gxbjZV
            UGNsSGlLQVBsVm9MYlIyTS9QdzlSZncKLS0tIG5LejNBcDZDZElvQmJjYUkrVUZ1
            RUxHbGdLNlJ4QWk1emxGUXg0QlpyLzAKm89Z9MrOB8pEkNqGunkzkEgcqgAG1flb
            Co8hBX/pzoD0qorHJqtiao66cV9SMQxUuPg5PQM/XcLoAZMKpZjELg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-12T21:28:07Z"
    mac: ENC[AES256_GCM,data:cjS0OnkfKqMKWlBcMSGtFnbKqDmJYAKhiJEQ+MqiTvpd1H9nKfmIzk5X/TdZk00MLx8fHGqFda3fcTANNoamv2BvCXg+WI1pihRldByalji2dCCtjEu9C9Zmm9yXK+/H1IXjyHSZd49ZwQGkRM+9AbW1Th6dzlfoQvn+YvkOG8Y=,iv:ec4QS5xAXR/AaUG5fvhq9RQXjXczncAr2fLhudnDKJ0=,tag:9evV9fULaMnK7LAazTXwZw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
