---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 79.7.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 12h
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    prometheus:
      prometheusSpec:
        retention: 7d
        storageSpec: {}
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 2Gi
      service:
        type: ClusterIP
    grafana:
      enabled: true
      adminPassword: admin
      service:
        type: LoadBalancer
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
    alertmanager:
      enabled: true
      service:
        type: ClusterIP
    kubeStateMetrics:
      enabled: true
    nodeExporter:
      enabled: true
    prometheusOperator:
      enabled: true
